services:
  dump1090:
    build: .
    container_name: dump1090
    restart: unless-stopped
    devices:
      - /dev/bus/usb/001/002:/dev/bus/usb/001/002
    ports:
      - "30002:30002"  # Raw ASCII output  
      - "30003:30003"  # SBS-1 BaseStation format
    privileged: true